export type ArgumentType =
    | "user"
    | "channel"
    | "boolean"
    | "integer"
    | "mentionable"
    | "number"
    | "role"
    | "string";
    
export type CategoryType = "command" | "listener";
export type CommandChannel = "guild" | "dm" | "all";
export type Emitter = "client" | "process" | "commandHandler";
export type ListenerCategory = Emitter;

export type ListenerType =
    // discord.js Events
    | "applicationCommandCreate"
    | "applicationCommandDelete"
    | "applicationCommandUpdate"
    | "channelCreate"
    | "channelDelete"
    | "channelPinsUpdate"
    | "channelUpdate"
    | "debug"
    | "emojiCreate"
    | "emojiDelete"
    | "emojiUpdate"
    | "error"
    | "guildBanAdd"
    | "guildBanRemove"
    | "guildCreate"
    | "guildDelete"
    | "guildIntegrationsUpdate"
    | "guildMemberAdd"
    | "guildMemberAvailable"
    | "guildMemberRemove"
    | "guildMembersChunk"
    | "guildMemberUpdate"
    | "guildUnavailable"
    | "guildUpdate"
    | "interaction"
    | "interactionCreate"
    | "invalidated"
    | "invalidRequestWarning"
    | "inviteCreate"
    | "inviteDelete"
    | "message"
    | "messageCreate"
    | "messageDelete"
    | "messageDeleteBulk"
    | "messageReactionAdd"
    | "messageReactionRemove"
    | "messageReactionRemoveAll"
    | "messageReactionRemoveEmoji"
    | "messageUpdate"
    | "presenceUpdate"
    | "rateLimit"
    | "ready"
    | "roleCreate"
    | "roleDelete"
    | "roleUpdate"
    | "shardDisconnect"
    | "shardError"
    | "shardReady"
    | "shardReonnecting"
    | "shardResume"
    | "stageInstanceCreate"
    | "stageInstanceDelete"
    | "stageInstanceUpdate"
    | "stickerCreate"
    | "stickerDelete"
    | "stickerUpdate"
    | "threadCreate"
    | "threadDelete"
    | "threadListSync"
    | "threadMembersUpdate"
    | "threadMemberUpdate"
    | "typingStart"
    | "userUpdate"
    | "voiceStateUpdate"
    | "warn"
    | "webhookUpdate"

    // Process events
    | "uncaughtException"
    | "unhandledRejection"

    // Player events
    | "songPlaying"
    | "songPaused"
    | "songResume"
    | "songEnded"
    | "queueEnded"
    | "disconnect"
    | "songNotFound"

    // Command handler events
    | "cooldown"
    | "missingPermissions";

export type MarkdownLanguage =
    | "javascript"
    | "typescript"
    | "python"
    | "lua"
    | "html"
    | "css"
    | "cmd"
    | "svg"
    | "ruby"
    | "c"
    | "c++"
    | "c#"
    | "md"
    | "json"
    | "asciidoc"
    | "autohotkey"
    | "bash"
    | "shell"
    | "coffeescript"
    | "cpp"
    | "diff"
    | "ini"
    | "ml"
    | "prolog"
    | "tex"
    | "xl"
    | "xml";
